In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
df=sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
X=df.drop('species',axis=1)
y=df['species']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
knn.score(X_test,y_test)

1.0

In [ ]:
from sklearn.svm import SVC
svc=SVC(gamma='auto',C=30,kernel='rbf')
svc.fit(X_train,y_train)
svc.score(X_test,y_test)

1.0

In [ ]:
# now use grid search cv
from sklearn.model_selection import GridSearchCV
classifier=GridSearchCV(svc,{'C':[1,10,20,30],'kernel':['rbf','linear']},cv=5,return_train_score=False)
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(C=30, gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [ ]:
classifier.cv_results_

{'mean_fit_time': array([0.00428462, 0.00387559, 0.00327463, 0.00225978, 0.00233564,
        0.00247231, 0.00237212, 0.00228295]),
 'std_fit_time': array([3.07647707e-04, 9.46702027e-05, 9.11659317e-04, 4.76420697e-05,
        2.35185638e-05, 3.44679905e-04, 6.24537639e-05, 3.08283981e-05]),
 'mean_score_time': array([0.003161  , 0.00293903, 0.00214858, 0.00173821, 0.00190296,
        0.00175304, 0.00178447, 0.00173163]),
 'std_score_time': array([1.12989017e-04, 3.28469165e-05, 4.24952594e-04, 3.15843342e-05,
        3.08647694e-04, 3.95396638e-05, 4.52655364e-05, 1.36337075e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [ ]:
results=pd.DataFrame(classifier.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004285,0.000308,0.003161,0.000113,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.003876,0.000095,0.002939,0.000033,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.003275,0.000912,0.002149,0.000425,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.002260,0.000048,0.001738,0.000032,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.002336,0.000024,0.001903,0.000309,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.002472,0.000345,0.001753,0.000040,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.002372,0.000062,0.001784,0.000045,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.002283,0.000031,0.001732,0.000014,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [ ]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
knn.score(X_test,y_test)
from sklearn.model_selection import GridSearchCV
classifier=GridSearchCV(knn,{'n_neighbors':[3,5,7,9,11]},cv=5,return_train_score=False)
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [3, 5, 7, 9, 11]})

In [ ]:
classifier.cv_results_

{'mean_fit_time': array([0.00269156, 0.00256443, 0.00216246, 0.00214639, 0.0021131 ]),
 'std_fit_time': array([2.78289102e-04, 5.51732181e-04, 2.40691792e-05, 2.57680083e-05,
        1.05584712e-05]),
 'mean_score_time': array([0.00378084, 0.004318  , 0.00317268, 0.00307961, 0.00310783]),
 'std_score_time': array([2.46910498e-04, 1.50944217e-03, 7.62868520e-05, 3.04655287e-05,
        3.38783992e-05]),
 'param_n_neighbors': masked_array(data=[3, 5, 7, 9, 11],
              mask=[False, False, False, False, False],
        fill_value=999999),
 'params': [{'n_neighbors': 3},
  {'n_neighbors': 5},
  {'n_neighbors': 7},
  {'n_neighbors': 9},
  {'n_neighbors': 11}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.93333333]),
 'split1_test_score': array([0.96666667, 1.        , 1.        , 1.        , 1.        ]),
 'split2_test_score': array([0.93333333, 0.93333333, 0.96666667, 0.96666667, 1.        ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 0.96666667]),
 'split4_test_score': array([1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.96666667, 0.97333333, 0.98      , 0.97333333, 0.98      ]),
 'std_test_score': array([0.02108185, 0.02494438, 0.01632993, 0.02494438, 0.02666667]),
 'rank_test_score': array([5, 3, 1, 3, 1], dtype=int32)}

In [ ]:
results=pd.DataFrame(classifier.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002692,0.000278,0.003781,0.000247,3,{'n_neighbors': 3},0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,5
1,0.002564,0.000552,0.004318,0.001509,5,{'n_neighbors': 5},0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,3
2,0.002162,0.000024,0.003173,0.000076,7,{'n_neighbors': 7},0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.002146,0.000026,0.003080,0.000030,9,{'n_neighbors': 9},0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,3
4,0.002113,0.000011,0.003108,0.000034,11,{'n_neighbors': 11},0.933333,1.000000,1.000000,0.966667,1.0,0.980000,0.026667,1

In [ ]:
results[['param_n_neighbors','mean_test_score']]

   param_n_neighbors  mean_test_score
0                  3         0.966667
1                  5         0.973333
2                  7         0.980000
3                  9         0.973333
4                 11         0.980000

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
classifier_r=RandomizedSearchCV((svc),{'C':[1,10,20,30],'kernel':['rbf','linear']},n_iter=4,cv=5,return_train_score=False)
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(C=30, gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [ ]:
classifier.cv_results_

{'mean_fit_time': array([0.00269156, 0.00256443, 0.00216246, 0.00214639, 0.0021131 ]),
 'std_fit_time': array([2.78289102e-04, 5.51732181e-04, 2.40691792e-05, 2.57680083e-05,
        1.05584712e-05]),
 'mean_score_time': array([0.00378084, 0.004318  , 0.00317268, 0.00307961, 0.00310783]),
 'std_score_time': array([2.46910498e-04, 1.50944217e-03, 7.62868520e-05, 3.04655287e-05,
        3.38783992e-05]),
 'param_n_neighbors': masked_array(data=[3, 5, 7, 9, 11],
              mask=[False, False, False, False, False],
        fill_value=999999),
 'params': [{'n_neighbors': 3},
  {'n_neighbors': 5},
  {'n_neighbors': 7},
  {'n_neighbors': 9},
  {'n_neighbors': 11}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.93333333]),
 'split1_test_score': array([0.96666667, 1.        , 1.        , 1.        , 1.        ]),
 'split2_test_score': array([0.93333333, 0.93333333, 0.96666667, 0.96666667, 1.        ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 0.96666667]),
 'split4_test_score': array([1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.96666667, 0.97333333, 0.98      , 0.97333333, 0.98      ]),
 'std_test_score': array([0.02108185, 0.02494438, 0.01632993, 0.02494438, 0.02666667]),
 'rank_test_score': array([5, 3, 1, 3, 1], dtype=int32)}

In [ ]:
results=pd.DataFrame(classifier.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002692,0.000278,0.003781,0.000247,3,{'n_neighbors': 3},0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,5
1,0.002564,0.000552,0.004318,0.001509,5,{'n_neighbors': 5},0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,3
2,0.002162,0.000024,0.003173,0.000076,7,{'n_neighbors': 7},0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.002146,0.000026,0.003080,0.000030,9,{'n_neighbors': 9},0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,3
4,0.002113,0.000011,0.003108,0.000034,11,{'n_neighbors': 11},0.933333,1.000000,1.000000,0.966667,1.0,0.980000,0.026667,1

In [ ]:
results_r = pd.DataFrame(classifier_r.cv_results_)
results_r[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       10       linear         0.973333
1       10          rbf         0.980000
2        1          rbf         0.980000
3        1       linear         0.980000

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import StackingClassifier
from sklearn.tree import DecisionTreeClassifier # Corrected from DecisionTree
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings('ignore')
df=sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
le=LabelEncoder()
Y_encoded=le.fit_transform(y)

In [ ]:
import seaborn as sns
df=sns.load_dataset('iris') # Reload df to ensure 'species' column is present
X=df.drop('species',axis=1)
y=df['species']

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,Y_encoded,test_size=0.2,random_state=42,stratify=Y_encoded)

In [ ]:
base_learners=[
    ('dt',DecisionTreeClassifier()),
    ('svc',SVC(probability=True,kernel='rbf',random_state=42)),
    ('lr',LogisticRegression(max_iter=1000))
]
meta_learner=LogisticRegression(max_iter=1000)
stacking_clf=StackingClassifier(estimators=base_learners,final_estimator=meta_learner,cv=5)
stacking_clf.fit(X_train,y_train)

StackingClassifier(cv=5,
                   estimators=[('dt', DecisionTreeClassifier()),
                               ('svc', SVC(probability=True, random_state=42)),
                               ('lr', LogisticRegression(max_iter=1000))],
                   final_estimator=LogisticRegression(max_iter=1000))

In [ ]:
y_pred=stacking_clf.predict(X_test)
accuracy_score(y_test,y_pred)

0.9666666666666667

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(
    n_estimators=100,
    criterion='gini',
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42
)
rf.fit(X_train,y_train)
y_pred=rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.9

In [ ]:
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier
from xgboost import XGBClassifier
ada_model=AdaBoostClassifier(n_estimators=100,random_state=42)
ada_model.fit(X_train,y_train)
y_pred=ada_model.predict(X_test)
accuracy_score(y_test,y_pred)

0.9333333333333333

In [ ]:
gb_model=GradientBoostingClassifier(n_estimators=100,random_state=42)
gb_model.fit(X_train,y_train)
y_pred=gb_model.predict(X_test)
accuracy_score(y_test,y_test)

1.0

In [ ]:
xgb_model=XGBClassifier(n_estimators=100,learning_rate=0.1,max_depth=3,random_state=42,use_label_encoder=False,eval_metric='mlogloss')
xgb_model.fit(X_train,y_train)
y_pred=xgb_model.predict(X_test)
accuracy_score(y_test,y_pred)

0.9333333333333333